### ISSUE TITLE
Error with Bootstrap Stylus Parsing

### ISSUE THREAD

**Issue by vlucas** [okcjs/thunderplains-hexo#11]
@the-simian think you can help on this one?

I get this error when I run `hexo generate`. Are you using hexo for stylus support, or stylus itself directly?

```
[error] HexoError: Render failed: stylesheets/bootstrap/bootstrap.css
CoercionError: /Users/vlucas/Code/thunderplains-hexo/themes/thunderplains/source/stylesheets/bootstrap/alerts.styl:43
   39| // Expand the right padding and account for the close button's positioning.
   40|
   41| .alert-dismissable {
   42|   padding-right: ($alert-padding + 20);
 > 43|
   44|   // Adjust close link position
   45|   .close {
   46|     position: relative;

cannot coerce 20 to ident
    at ".alert-dismissable " (/Users/vlucas/Code/thunderplains-hexo/themes/thunderplains/source/stylesheets/bootstrap/alerts.styl:42)

    at Ident.Node.coerce (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/nodes/node.js:246:11)
    at Ident.coerce (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/nodes/ident.js:123:36)
    at Ident.operate (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/nodes/ident.js:149:49)
    at Evaluator.visitBinOp (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:557:28)
    at Evaluator.Visitor.visit (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:157:18)
    at Evaluator.visitExpression (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:620:26)
    at Evaluator.Visitor.visit (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:157:18)
    at Evaluator.visitExpression (/Users/vlucas/Code/thunderplains-hexo/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:620:26)
```

**Comment by vlucas** [comment]
Could be related to: https://github.com/LearnBoost/stylus/issues/310

**Comment by vlucas** [comment]
So weird. I am not sure what to think here, but the site generation process is irratic. I kept running into stylus errors, so I just kept running `hexo generate` over and over and kept getting different errors. Eventually there were no errors and it generated successfully, so I deployed. Super weird.

**Comment by the-simian** [comment]
this was weird a couple times for me. It was the variables file...

so for some reason hexo server like, runs them all at once. however, hexo generate seems to run each file in some kind of functional closure. I got around it by importing the variable file into the other files and it ran correctly. This was using the hexo stylus.

Still had better luck than the sass - which I simply coul d not get to work at all.
